import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Section from '../components/atoms/Section/section'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | UI Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Section>
          <p>Hallo Word !!!</p>
        </Section>
      </main>
    </div>
  )
}
